apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: wiz-exercise
  labels:
    app: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      serviceAccountName: todo-app-sa
      containers:
        - name: todo-app
          # Replace with your ECR repo URL output from Terraform
          image: 278635088475.dkr.ecr.us-east-1.amazonaws.com/wiz-exercise-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-connection
                  key: MONGO_URI
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
